blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/developjik/developjik-workspace/discussions
    about: ì§ˆë¬¸ì´ë‚˜ ì•„ì´ë””ì–´ì— ëŒ€í•´ í† ë¡ í•˜ê³  ì‹¶ìœ¼ì‹œë©´ ì—¬ê¸°ì„œ ì‹œì‘í•˜ì„¸ìš”.
  - name: ğŸ“– Documentation
    url: https://developjik-workspace-docusaurus-developjiks-projects.vercel.app
    about: í”„ë¡œì íŠ¸ ë¬¸ì„œì™€ ê°€ì´ë“œë¥¼ í™•ì¸í•˜ì„¸ìš”.